name: onpush_example
description: This is example project to display error <https://github.com/dart-lang/angular/issues/1816>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_forms: ^2.1.3

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.0.0
