name: onpush_example
description: This is example project to display error <https://github.com/dart-lang/angular/issues/1816>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.2.0

dev_dependencies:
  build_runner: ^1.5.0
  angular_forms: any
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
